# Generated by Django 5.1.1 on 2025-06-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0006_load_steps_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('expense', 'Expense'), ('income', 'Income'), ('equity', 'Equity')], max_length=20, verbose_name='Account Type')),
                ('category_detail', models.CharField(choices=[('cash_equivalent', 'Cash Equivalent'), ('account_receivable', 'Account Receivable'), ('current_asset', 'Current Asset'), ('non_current_asset', 'Non-Current Asset'), ('fixed_asset', 'Fixed Asset'), ('current_liability', 'Current Liability'), ('account_payable', 'Account Payable'), ('non_current_liability', 'Non-Current Liability'), ('equity', 'Owners Equity'), ('income', 'Income'), ('other_income', 'Other Income'), ('expense', 'Expense'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('depreciation', 'Depreciation'), ('amortization', 'Amortization'), ('other_expense', 'Other Expense')], max_length=30, verbose_name='Account Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Account Categories',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5')], default='1', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('account_number', models.CharField(help_text='Not to be confused with bank a/c number', max_length=100, unique=True, verbose_name='Account Code/Number')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted', verbose_name='System Account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='payroll.bank')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='finance.account', verbose_name='Parent Account')),
                ('account_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.accountcategory', verbose_name='Account Detail')),
            ],
            options={
                'indexes': [models.Index(fields=['account_name'], name='finance_acc_account_aec444_idx'), models.Index(fields=['account_number'], name='finance_acc_account_932be5_idx'), models.Index(fields=['account_category'], name='finance_acc_account_3a50ee_idx'), models.Index(fields=['parent_account'], name='finance_acc_parent__4795fd_idx')],
            },
        ),
    ]
