# Generated by Django 5.1.1 on 2025-06-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    def load_account_categories(apps, schema_editor):
        AccountCategory = apps.get_model('finance', 'AccountCategory')
        categories = [
            # Asset class
            {'type': 'asset', 'category': 'cash_equivalent'},
            {'type': 'asset', 'category': 'account_receivable'},
            {'type': 'asset', 'category': 'current_asset'},
            {'type': 'asset', 'category': 'non_current_asset'},
            {'type': 'asset', 'category': 'fixed_asset'},
            # Liability class
            {'type': 'liability', 'category': 'current_liability'},
            {'type': 'liability', 'category': 'account_payable'},
            {'type': 'liability', 'category': 'non_current_liability'},
            # Equity class
            {'type': 'equity', 'category': 'equity'},
            # Income class
            {'type': 'income', 'category': 'income'},
            {'type': 'income', 'category': 'other_income'},
            # Expense class
            {'type': 'expense', 'category': 'expense'},
            {'type': 'expense', 'category': 'cost_of_goods_sold'},
            {'type': 'expense', 'category': 'operating_expense'},
            {'type': 'expense', 'category': 'depreciation'},
            {'type': 'expense', 'category': 'amortization'},
            {'type': 'expense', 'category': 'other_expense'},

        ]

        for category in categories:
            AccountCategory.objects.create(category_type=category['type'], category_detail=category['category'])

    dependencies = [
        ('finance', '0002_transaction_and_ledger_models_created_student_modified'),
    ]

    operations = [
        migrations.RunPython(load_account_categories)
    ]
