# Generated by Django 5.1.1 on 2025-06-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_load_account_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
