# Generated by Django 5.1.1 on 2025-06-04 11:26

from django.db import migrations

def load_levels(apps, schema_editor):
    Level = apps.get_model('finance', 'Level')
    # define levels for a University College in a dict eg. 50, 100 💡 
    levels = [
        {'name': '50'},
        {'name': '100'},
        {'name': '200'},
        {'name': '300'},
        {'name': '400'},
        {'name': '500'},
        {'name': '600'},
        {'name': '700'},
        {'name': '800'},
        {'name': '900'},
    ]
    for level in levels:
        Level.objects.create(name=level['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_load_countries'),
    ]

    operations = [
        migrations.RunPython(load_levels)
    ]
