# Generated by Django 5.1.1 on 2025-05-26 09:34

import django.db.models.deletion
import django_quill.fields
import hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0003_grade_step_renamed_to_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow multiple documents of this type per employee?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entitlement', models.FloatField()),
                ('method', models.CharField(choices=[('accrual', 'Accrual Method'), ('fixed', 'Static Annual Allotment')], default='accrual', max_length=10)),
                ('allow_rollover', models.BooleanField(default=False, verbose_name='Allow Rollover')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalIDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, null=True, unique=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title/Rank')),
                ('level', models.CharField(max_length=100, null=True, verbose_name='Hierarchy Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('title', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('employee_id', models.CharField(max_length=12, null=True, unique=True, verbose_name='Staff ID')),
                ('dob', models.DateField(null=True, verbose_name='Birth Date')),
                ('id_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='ID Number')),
                ('photo', models.ImageField(default='avatar.png', null=True, upload_to=hr.models.employee_photo_upload_path)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('account_number', models.CharField(max_length=24, null=True, unique=True, verbose_name='Account Number')),
                ('branch', models.CharField(max_length=254, null=True, verbose_name='Branch')),
                ('tin', models.CharField(max_length=24, null=True, unique=True, verbose_name='TIN No.')),
                ('ssnit', models.CharField(max_length=24, null=True, unique=True, verbose_name='SSNIT No.')),
                ('hire_date', models.DateField(verbose_name='Hired Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('probation', 'Probation'), ('retired', 'Retired'), ('resigned', 'Resigned')], default='active', max_length=10)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractual', 'Contractual'), ('temporary', 'Temporary')], default='full_time', max_length=12)),
                ('tax_relief', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tax Relief')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='payroll.bank')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.designation')),
                ('salary_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='payroll.salarygrade', verbose_name='Salary Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.documenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds'), ('GHS', 'Ghanaian Cedi')], default='GHS', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsibilities', django_quill.fields.QuillField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hr.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.job'),
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='hr.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='hr.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='hr.job')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('days_requested', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrued_days', models.FloatField(default=0.0)),
                ('used_days', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.nationalidtype', verbose_name='National ID'),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('project_management', 'Project Management & Leadership'), ('marketing', 'Marketing & Sales'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('design', 'Design & Creative'), ('customer_service', 'Customer Service & Support'), ('operations', 'Operations & Supply Chain'), ('legal', 'Legal & Compliance'), ('soft_skills', 'Soft Skills'), ('languages', 'Languages')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_for_jobs', to='hr.skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='hr.skill'),
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Note: SMS will prepend staff ID', null=True)),
                ('sms_date', models.DateTimeField(verbose_name='SMS Date & Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched')], default='pending', max_length=10)),
                ('department', models.ManyToManyField(related_name='sms', to='hr.department')),
                ('job', models.ManyToManyField(related_name='sms', to='hr.job')),
                ('salary_grade', models.ManyToManyField(related_name='sms', to='payroll.salarygrade', verbose_name='Salary Grade')),
            ],
            options={
                'verbose_name_plural': 'Sms',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name', models.CharField(max_length=100, verbose_name='Guarantor Name')),
                ('guarantor_phone_number', models.CharField(max_length=15, unique=True, verbose_name='Guarantor Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'guarantor_name', 'guarantor_phone_number')},
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'last_name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone_number'], name='phone_number_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('id_type', 'id_number')},
        ),
    ]
