# Generated by Django 5.1.1 on 2025-06-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_load_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=10, verbose_name='Marital Status'),
        ),
    ]
