# Generated by Django 5.1.1 on 2025-06-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_employmenttype_model_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employment_type',
        ),
    ]
