# Generated by Django 5.1.1 on 2025-06-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employment_type_field_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.employmenttype', verbose_name='Employment Type'),
        ),
    ]
