# Generated by Django 5.1.1 on 2025-06-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    def load_employment_types(apps, schema_editor):
        EmploymentType = apps.get_model('hr', 'EmploymentType')
        EmploymentType.objects.bulk_create([
            EmploymentType(name='Full-time'),
            EmploymentType(name='Part-time'),
            EmploymentType(name='Contract'),
            EmploymentType(name='Internship'),
            EmploymentType(name='Temporary'),
        ])

    dependencies = [
        ('hr', '0010_employment_type_field_added_as_foreign_key'),
    ]

    operations = [
        migrations.RunPython(load_employment_types, reverse_code=migrations.RunPython.noop)
    ]
