# Generated by Django 5.1.1 on 2025-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_blank_attribute_added_to_tin_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reg_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='reg_lockout_time',
            field=models.DateTimeField(blank=True, help_text='Time when the user was locked out due to too many registration attempts', null=True),
        ),
    ]
