# Generated by Django 5.1.1 on 2025-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_registration_attempts_fields_added_to_ensure_consistency_accross_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEditableFieldsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
