# Generated by Django 5.1.1 on 2025-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_model_to_control_staff_editable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='request_source',
            field=models.CharField(choices=[('portal', 'Staff Portal'), ('admin', 'Admin Side')], default='portal', max_length=20),
        ),
    ]
