# Generated by Django 5.1.1 on 2025-05-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_salary_grade_n_step_bank_tax_models_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together={('grade', 'grade_step')},
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='step',
        ),
    ]
