# Generated by Django 5.1.1 on 2025-05-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_step_field_removed_from_salarygrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarygrade',
            old_name='grade_step',
            new_name='step',
        ),
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together={('grade', 'step')},
        ),
    ]
