# Generated by Django 5.1.1 on 2025-06-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_load_banks_data'),
    ]

    def load_steps(apps, schema_editor):
        SalaryStep = apps.get_model('payroll', 'SalaryStep')
        entries = []
        for i in range(1, 10):
            entries.append(SalaryStep(step=i))
        SalaryStep.objects.bulk_create(entries)

    operations = [
        migrations.RunPython(load_steps)
    ]
