# Generated by Django 5.1.1 on 2025-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_load_employment_types'),
        ('payroll', '0006_load_steps_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryitem',
            name='condition',
        ),
        migrations.AddField(
            model_name='salaryitem',
            name='employment_type',
            field=models.ManyToManyField(blank=True, related_name='salary_items', to='hr.employmenttype', verbose_name='Employment Type'),
        ),
    ]
