# Generated by Django 5.1.1 on 2025-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_load_employment_types'),
        ('payroll', '0007_employment_type_replaced_with_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('process_month', 'process_year', 'payment_rate', 'description')},
        ),
        migrations.AddField(
            model_name='payroll',
            name='employment_type',
            field=models.ManyToManyField(blank=True, related_name='payrolls', to='hr.employmenttype', verbose_name='Employment Type'),
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='condition',
        ),
    ]
