# Generated by Django 5.1.1 on 2025-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employment_type_replaced_with_condition_in_payroll_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='request_source',
            field=models.CharField(choices=[('portal', 'Staff Portal'), ('admin', 'Admin Side')], default='portal', max_length=20),
        ),
    ]
